### ISSUE TITLE
Cards aren't saving on the correct way

### ISSUE THREAD

**Issue by DiegoTc** [ebadawy/bone101#3]
Position of the cards aren't correct
Real Card postions are as follow:
bone101_html_Description
bone101_code_Code
bone101_html_ss
bone101_html_Hope you like it

But they were save on this way

According to gist: https://gist.github.com/DiegoTc/5cffc9f94f8a61daffad

https://gm1.ggpht.com/pxuQ1cKYvGSIqw1T85A_rdvi1DJoKQHSWA0AnPfEnQugLcGTl-WZrqgQniYCyi1M-KLvD0wshkFboDJz5fFbCzjXdqJcSaqfIhYmPEJbQ8Atwfb7YHbRE93ZGu2auzgr0rav-mOgFEfS_z1aicHxcC1t7q7_B2vNh_ldcJms9Hhh6VgAhtK0LiD2KliqWwX88wwjXPx77EhWQ0DXlfAdTmxr9zgr2PMduVVQG0o-L9Ycrx8tcGTKjRDgs6B0-qKCT9qhdm981p6nEkuPLcCcnRdxqEljQRjfNGyRJ9YcnJcJzM3A4lMyxfOwfm6wEWSqHkihydhegpDuFtD_Zml7E2-fSxomMOktHsxLLpu2NE8Zm_aj7L99K-erWMEEiiXnE5EjbnY29S3q-u5RurXquMBfLg1ri_qtxIFL74naaB6xmUkPiMxlrHBa4d2g5otwqOiCu9mrATg7mzABPehMA4b49uH-e8GyfuwUHUM285YuyvOpVFpPi7xe31-BLJvXAhVC3yRZXCQSKLMWR9ENVfI0mLr7-9FaHsraDNDnloNBcekYWJlLc0poPQ9KcDvPBP_quATN-ZyTLpIYbJiV64D068cWT11oN5PhYQ=w1277-h561-l75-ft

**Comment by ebadawy** [comment]
I think it should be now fixed.
